#!/bin/sh
ABI=4.6.2
JOBS=16

TOOLCHAIN="arm-eabi-linaro-4.6.2"
CROSS_COMPILE_PREFIX=arm-eabi-

PATH="/home/minus13/android/kernel/toolchains/$TOOLCHAIN/bin:$PATH"

time make -j$JOBS ARCH=arm CROSS_COMPILE=$CROSS_COMPILE_PREFIX EXTRA_AFLAGS="-mfpu=neon"
